export default {
    SET_DATE: 'SET_DATE',
    MOVE: 'MOVE',
    ADD: 'ADD',
    DELETE: 'DELETE',
    CHANGE_GROUP: 'CHANGE_GROUP',
    CHANGE_TEACHER: 'CHANGE_TEACHER',
    CHANGE_CLASS_NUMBER: 'CHANGE_CLASS_NUMBER',
    CHANGE_LESSON: 'CHANGE_LESSON',
    CHANGE_ARTICLE: 'CHANGE_ARTICLE',
};
